#!/bin/bash

# Element [SFlags "Desc" "Name" "Value" MX MY TX TY TDir TScale TSFlags]
#       Pin [rX  rY   Thickness Clearance Mask Drill "Name" "Number" SFlags]

Thickness=6000
Clearance=1000
Mask=6500
Drill=2900

printf '\n\n# +++++ Generated by %s +++++\n\n' "$0"
printf 'Element ["" "SBLCDA2 LCD" "" "" 10 10 -1000 1000 0 100 ""] (\n'

for pin in `seq 1 48` ; do

	if [ x"$pin" == x"1" ] ; then
		SFlags="square"
	else
		SFlags=""
	fi

	if [ 25 -gt "$pin" ] ; then
		rX=0
		rY=$(( (pin-1) * 7874 ))
	else
		rX=110000
		rY=$(( (48-pin) * 7874 ))
	fi

	printf '\tPin [ %6d %6d %s %s %s %s "%d" "%d" "%s" ]\n' \
		$rX $rY $Thickness $Clearance $Mask $Drill $pin $pin $SFlags
done

printf ')\n'
printf '# ---------------------------\n'
